### ISSUE TITLE
save_attachments should rewind before reading

### ISSUE THREAD

**Issue by phaza** [jnunemaker/joint#1]
I just spent no less than two hours trying to figure out why the file i saved in gridfs had size 0, only to realize out of nowhere that read continues from where the file pointer is. Hence, it was trying to read from the end of my freshly written and still open Tempfile.

Anyway, just doing a simple tmp_file.rewind before passing the instance of to Joint did the trick.
I would presume this rewind is something Joint should do in Joint#save_attachments, and hence I'm classifying this as a bug.

**Comment by jnunemaker** [comment]
yep, aware of this. I can add it today.

**Comment by jnunemaker** [comment]
this and a few other things are fixed in 0.2
