### ISSUE TITLE
Avoid reading whole IO into memory

### ISSUE THREAD

**Issue by mrcljx** [jnunemaker/joint#10]
Mongo::Grid reads IOs chunkwise to avoid unnecessary memory usage. Is there a particular reason why `save_attachments` rewinds and reads the `io` into memory?

See: https://github.com/jnunemaker/joint/blob/master/lib/joint/instance_methods.rb#L22

**Comment by bkeepers** [comment]
Thanks for pointing that out.  If I get rid of the read, one of the tests fails. I don't have time to look into it today, but if you have time, a patch would be appreciated! :)

```

  1) Error:
test: Assigning joint io instance should work. (JointTest):
ArgumentError: wrong number of arguments (1 for 0)
    /Users/brandon/.rvm/gems/ree-1.8.7-2011.03/gems/mongo-1.3.1/lib/../lib/mongo/gridfs/grid_io.rb:128:in `read'
    /Users/brandon/.rvm/gems/ree-1.8.7-2011.03/gems/mongo-1.3.1/lib/../lib/mongo/gridfs/grid_io.rb:128:in `write'
    /Users/brandon/.rvm/gems/ree-1.8.7-2011.03/gems/mongo-1.3.1/lib/../lib/mongo/gridfs/grid.rb:72:in `put'
    /Users/brandon/projects/joint/lib/joint/instance_methods.rb:22:in `save_attachments'
```

**Comment by mrcljx** [comment]
Pull request is in #11.
