### ISSUE TITLE
Need MM 0.9.2-compatible Joint Gem released

### ISSUE THREAD

**Issue by jamieorc** [jnunemaker/joint#12]
Upgrading an app to Rails 3/MM 0.9.2 and using Bundler, got an error for Joint 0.5.5 which has a dependency on MM 0.8.6. Can you push a new tag of Joint to rubygems with the MM 0.9.X dependency?

**Comment by bkeepers** [comment]
Yep, we'll try to get out a new version today or tomorrow.

**Comment by jamieorc** [comment]
Many thanks!

**Comment by jnunemaker** [comment]
Yep. I will try to do this today, but I'm kind of swamped.

**Comment by jnunemaker** [comment]
Released 0.6.

**Comment by jamieorc** [comment]
Cheers!
