### ISSUE TITLE
can't convert ActionController::TestUploadedFile into String

### ISSUE THREAD

**Issue by oliverbarnes** [jnunemaker/joint#3]
Hi John, got uploads working with Joint (thanks for the pointers on twitter, btw), but I'm having trouble getting the tests right. I've posted the issue on StackOverflow, not sure it's on Joint's side or Rails's (or my own, of course ;):

http://stackoverflow.com/questions/4051726/testing-file-uploads-in-rails-cant-convert-actioncontrollertestuploadedfile-i

Testing this at the controller level since it's an api call with no view...
- Oliver

**Comment by jnunemaker** [comment]
Closing as it was answered on SO.
